### ISSUE TITLE
Python client API in Episuite

### ISSUE THREAD

**Issue by perone** [gisumd/COVID-19-API-Documentation#10]
Hi, just to let you know that I added a Python client for the API in [Episuite](https://perone.github.io/episuite) project, examples on the [tutorial](https://perone.github.io/episuite/symptom_survey.html) in case you want to let users know about it.

**Comment by andGarc** [comment]
@perone Thanks! We have added a link to your package under the tutorial [section](https://gisumd.github.io/COVID-19-API-Documentation/docs/tutorials/episuite.html).
